name: djamo-take-home-test

services:

  thirdparty:
    build: ./thirdpartymock
    ports:
      - "3000:3000"

  client:
    build: ./client
    environment:
      YOUR_API: http://api:3000
    ports:
      - "3100:3100"

  api:
    image: node:20.11.1
    container_name: api
    restart: always
    working_dir: /app
    environment:
      BASE_URL: http://api:3000
      THIRD_PARTY_URL: http://thirdparty:3000
      CLIENT_URL: http://client:3100
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/djamo?schema=public"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "redis"
      REDIS_DATABASE: "redis"
      PROCESS_TRX_QUEUE: "PROCESS_TRANSACTION"
      UPDATE_TRX_QUEUE: "UPDATE_TRANSACTION"
    ports:
      - "3200:3000"
    links:
      - postgres
      - redis
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api:/app
    command: bash -c "yarn && yarn build && yarn start:prod"

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "djamo"
    volumes:
      - data:/var/lib/postgres 
      - ./api/prisma/migrations/20241206141213_init:/docker-entrypoint-initdb.d # migrate db
    ports:
      - "5432:5432"
   
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  data:
  cache:
